### PR TITLE
Naive fix for optional members

### LINKED ISSUE #33: Expansion members not registered to Optional types
### Intro
Members added to Expansions T are not added to T? types.

### Reproduction Script
```zs
public expand string {
	public someTest() as string => this;
}

var x as string = "Not-Optional";

println(x);
println(x.someTest());

var y as string? = "Optional";

println(y);
//println(y.someTest()); //ERROR OptionalTest.zs:13:8: OptionalTest.zs:8:8: No such member: someTest
```

### PR DESCRIPTION
**Pull request by jaredlll08**
Naive fix, this doesn't *register* them to the optional type, but it will get them when an optional needs them from the base type.

This fixes #33

### CODE REVIEW

**Review by kindlich — APPROVED** [review]

File: CodeModel/src/main/java/org/openzen/zenscript/codemodel/expression/Expression.java [hunk 1]
```diff
@@ -142,8 +141,11 @@ public Expression call(CodePosition position, TypeScope scope, List<TypeID> hint
 
 	@Override
 	public IPartialExpression getMember(CodePosition position, TypeScope scope, List<TypeID> hints, GenericName name) throws CompileException {
-		TypeMembers members = scope.getTypeMembers(type);
-		IPartialExpression result = members.getMemberExpression(position, scope, this, name, false);
+		IPartialExpression result = scope.getTypeMembers(type).getMemberExpression(position, scope, this, name, false);
+		// If the type is optional, check if the member exists on the normal type.
+		if (result == null && type.isOptional())
+			result = scope.getTypeMembers(type.withoutOptional()).getMemberExpression(position, scope, this, name, false);
+
```
Comment (stanhebben) [inline CodeModel/src/main/java/org/openzen/zenscript/codemodel/expression/Expression.java]: The logic makes sense, but I believe it is not at the right place. I believe this should be in the TypeMembers class instead.

There might be other code that retrieves a member, and putting the logic here would cause type member resolution to be inconsistent.

**Review by stanhebben — CHANGES_REQUESTED** [review]

**Review by stanhebben — APPROVED** [review]
